#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#    url: /openapi/tenx-banking.yaml
#    config-url: /v3/api-docs/swagger-config
management:
  endpoint:
    health:
      show-details: always
